### ISSUE TITLE
Составить интро

### ISSUE THREAD

**Issue by galka-hub** [galka-hub/homepage#4]
Составить интро (вступление), где в 2-4 предложениях описать, что заказчик делает, что нравится делать, что хочется делать лучше, что важно делать, и т.д.

**Comment by alex7999** [comment]
good

**Comment by alex7999** [comment]
Я очень целеустремленный человек и знаю что если чего-то очень сильно захотеть, то всего можно добиться. Хочу выучить в совершенстве английский язык. Так же хочу попробовать выучить французский и итальянский языки.
