### ISSUE TITLE
Составить блок контактной информации

### ISSUE THREAD

**Issue by galka-hub** [galka-hub/homepage#5]
Ссылки на соцсети (Facebook или Instagram, и т.п.), номер телефона или адрес электронной почты, т.п. Может не все ссылки в мире, а только те, которые действительно уместны.

**Comment by alex7999** [comment]
nice

**Comment by alex7999** [comment]
https://www.linkedin.com/in/galina-petreacova-81658a1b7/
galka7462@gmail.com
