### ISSUE TITLE
Составить таймлайн

### ISSUE THREAD

**Issue by galka-hub** [galka-hub/homepage#6]
Составить список всех (важных) жизненных событий, памятных дат, достижений, периодов, которые дали приятный и неприятный опыт, и т.п. В этом конкретном случае длинных списков не бывает, бывают плохо свернутые, поэтому пакуем сюда всё подряд, а про "лишние" события можно будет промолчать позже. Список должен быть систематизирован и отсортирован таким образом, чтоб читатель быстро понял "паттерн" и мог легко ориентироваться в пространстве и времени этого резюме.

**Comment by alex7999** [comment]
ok

**Comment by alex7999** [comment]
2010 год- окончила Одесский государственный медицинский университет.
2010 год- получила работу в родильном доме.
2010 год - вышла замуж)
2012 год - родила первенца)
2020 год - решила кардинально все поменять и окончила онлайн курсы "Основы тестирования ПО" от тренингового центра QA TestLab. 
2021 год- самостоятельно начала изучать язык программирования Java.
