### ISSUE TITLE
Составить дополнительные информационные блоки

### ISSUE THREAD

**Issue by galka-hub** [galka-hub/homepage#7]
Можно сделать резюме менее формальным, добавив дополнительные блоки, которые содержат полезную информацию, но подают её в "развлекательной" форме. Например, что нравится и не нравится, сильные и слабые стороны, перечень навыков или хобби, инфографика или же интерактивные модули, и т.п. Стоит написать контент такого блока раньше, чем начинать верстку, потому что его размеры будут влиять на размещение элементов на странице.

**Comment by alex7999** [comment]
hi

**Comment by galka-hub** [comment]
Thank you

**Comment by alex7999** [comment]
ЯЗЫКИ-РУССКИЙ, УКРАИНСКИЙ, АНГЛИЙСКИЙ

НАВЫКИ И УМЕНИЯ - Знания уровней и видов тестирования. Знание классификации тестирования. Понимание и опыт написания тестовой документации (тест-кейс, тест-план, баг-репорт). Знание основных техник тест-дизайна. Понимание жизненного цикла ПО. Знание методологий разработки ПО. Опыт работы с баг-трекинговой системой Mantis, Jira. 

ХАРАКТЕР. Присутствуют такие черты характера как : доброжелательность; трудолюбие; коммуникабельность .
Отсутствуют: конфликтность; склонность к безделью;  замкнутость. В общем ангельский характер).

НРАВИТСЯ - спорт, вождение автомобиля, греться на солнышке и суши)

НЕ НРАВИТСЯ - летать на самолете

ХОЧУ - построить большой дом
